use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // Get the output directory for generated files
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("exercises_data.rs");
    let download_path = Path::new(&out_dir).join("exercises.json");

    // URL to download the exercises.json from
    const EXERCISES_JSON_URL: &str = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json";

    println!("cargo:warning=Downloading exercises.json from {}", EXERCISES_JSON_URL);

    // Try to download the JSON file using curl or wget
    let download_success = if Command::new("curl")
        .args(&[
            "-L",
            "-o",
            download_path.to_str().unwrap(),
            EXERCISES_JSON_URL,
        ])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
    {
        true
    } else if Command::new("wget")
        .args(&[
            "-O",
            download_path.to_str().unwrap(),
            EXERCISES_JSON_URL,
        ])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
    {
        true
    } else {
        false
    };

    // Read the exercises JSON
    let exercises_json = if download_success && download_path.exists() {
        println!("cargo:warning=Successfully downloaded exercises.json");
        fs::read_to_string(&download_path)
            .expect("Failed to read downloaded exercises.json file")
    } else {
        // If download fails, check if there's a cached version in assets/ as fallback
        println!("cargo:warning=Failed to download exercises.json. Checking for local fallback...");
        let fallback_path = "assets/exercises.json";
        if Path::new(fallback_path).exists() {
            println!("cargo:warning=Using fallback local file: {}", fallback_path);
            fs::read_to_string(fallback_path)
                .expect("Failed to read fallback exercises.json file")
        } else {
            panic!("Failed to download exercises.json and no local fallback found. Please ensure curl or wget is installed.");
        }
    };

    // Parse the JSON to validate it's correct
    let exercises: serde_json::Value = serde_json::from_str(&exercises_json)
        .expect("Failed to parse exercises.json");

    // Verify it's an array
    if !exercises.is_array() {
        panic!("exercises.json must contain an array of exercises");
    }

    // Generate Rust code that will contain the JSON as a static string
    // Using a raw string literal with custom delimiter to avoid escaping issues
    let generated_code = format!(
        r#####"
// This file is automatically generated by build.rs
// Do not edit manually

#[allow(dead_code)]
pub const EXERCISES_JSON: &str = r####"{}"####;
"#####,
        exercises_json
    );

    // Write the generated code to a file
    fs::write(&dest_path, generated_code)
        .expect("Failed to write generated exercises data");
}
