use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Get the output directory for generated files
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("exercises_data.rs");

    // Path to the exercises.json file in assets/
    let exercises_json_path = "assets/exercises.json";

    // Tell Cargo to rerun this build script if the exercises.json changes
    println!("cargo:rerun-if-changed={}", exercises_json_path);

    // Read the JSON file
    let exercises_json = fs::read_to_string(exercises_json_path)
        .expect("Failed to read exercises.json file");

    // Parse the JSON to validate it's correct
    let exercises: serde_json::Value = serde_json::from_str(&exercises_json)
        .expect("Failed to parse exercises.json");

    // Verify it's an array
    if !exercises.is_array() {
        panic!("exercises.json must contain an array of exercises");
    }

    // Generate Rust code that will contain the JSON as a static string
    // Using a raw string literal with custom delimiter to avoid escaping issues
    let generated_code = format!(
        r#####"
// This file is automatically generated by build.rs
// Do not edit manually

pub const EXERCISES_JSON: &str = r####"{}"####;
"#####,
        exercises_json
    );

    // Write the generated code to a file
    fs::write(&dest_path, generated_code)
        .expect("Failed to write generated exercises data");
}
