# [application]
# android_main_activity = "android/MainActivity.kt"
# asset_dir = ""
# ios_entitlements = ""
# ios_info_plist = ""
# macos_entitlements = ""
# macos_info_plist = ""
# out_dir = ""
# public_dir = ""
# tailwind_input = ""
# tailwind_output = ""

[bundle]
category = "Sports"
copyright = "Copyright 2026 Guilhem Fauré"
icon = ["logo.svg"]
identifier = "com.gfaure.logout"
long_description = "A simple, efficient, cross-platform workout logging application with 800+ exercises built-in, by Guilhem Fauré"
publisher = "Guilhem Fauré"
# resources = [""]
short_description = "Workout Logger"

# [deep_links] TODO See if this can replace/lighten custom implementation
# hosts = []
# paths = []
# schemes = []

[permissions]
# background-location.description = "Tracking cardio exercises distance?"
# calendar = { access = "read-write", description = "Workout plannings?" } 
# health = { access = "read-write", description = "Integration?" } 
# local-network.description = "P2P Syncing?" 
# location = { precision = "fine", description = "Workout loc/distance?" } 
# media-library.description = "Import/Export Exercises/Sessions" 
# motion.description = "Tracking cardio exercises distance?" 
# nerby-wifi.description = "P2P Syncing?" 
notifications.description = "Rest/Exercise duration alerts"
photos = { access = "read", description = "Custom exercises images" } 

[android]
compile_sdk = 36
# features = [""]
# foreground_service_types = [""]
# manifest = "android/AndroidManifest.xml"
min_sdk = 28
# proguard_rules = [""]
target_sdk = 36

[android.permissions]
internet.description = "Download exercises and translations"
wake_lock.description = "Keep screen on during workouts"

[android.application]
# Ensure WebView reports system dark/light setting to CSS `prefers-color-scheme`
theme = "@style/Theme.AppCompat.DayNight.NoActionBar"

[web]
# app.base_path = "/"
app.title = "LogOut - Workout Logger"
pre_compress = true

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["assets", "public", "src"]
