[application]
name = "LogOut"
default_platform = "web"

[bundle]
name = "LogOut"
identifier = "com.gfaure.logout"
publisher = "gfaure"
icon = ["logo.png"]

[web.app]
title = "LogOut - Workout Logger"

[web.watcher]
reload_html = true
index_on_404 = true

[android]
theme = "Theme.AppCompat.NoActionBar"
targets = ["aarch64-linux-android", "x86_64-linux-android"]
