on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          extra-substituters = https://cache.garnix.io
          extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
    - uses: cachix/cachix-action@v16
      with:
        name: gfauredev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: nix develop --command cargo check # Install dependencies
      continue-on-error: true
