on:
  # schedule: [cron: '0 0 * * *'] # Each Midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  audit-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          extra-substituters = https://cache.garnix.io
          extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: nix develop -c cargo deny check

  test-mutants:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          extra-substituters = https://cache.garnix.io
          extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: nix develop -c cargo mutants --no-shuffle \
        --caught --timeout 300 --exclude "src/components/*"

  e2e-android:
    runs-on: macos-latest # Apple Silicon for native ARM64 emulation
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
    # - uses: wimpysworld/nothing-but-nix@v10
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          extra-substituters = https://cache.garnix.io
          extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: gh release download --pattern "*.apk" --dir . # From CD
      env:
        GH_TOKEN: ${{ github.token }}
    # Set up ARM64 Android emulator and run tests
    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        arch: arm64-v8a
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
          adb install -r LogOut.arm64-v8a.apk
          nix run .#androidE2eTest
    - if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: maestro-android-report
        path: ~/.maestro/tests
